AllCops:
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*
